### ISSUE TITLE
Using with psycopg 3 pools throws thread error

### ISSUE THREAD

**Issue by dmvieira** [pgvector/pgvector-python#64]
I'm using pgvector-python with psycopg 3, but every connection need configuration creating vector extension and executing `register_vector`.

Now we are using this configuration for pools:

```python
ConnectionPool(
            kwargs=our_database_config,
            max_size=20,
            check=ConnectionPool.check_connection,
            configure=register_pgvector,
            open=True
        )
```

With `register_pgvector` as

```python
def register_pgvector(conn: Connection):
    stmt = 'CREATE EXTENSION IF NOT EXISTS vector'
    with conn.cursor() as cur:
        cur.execute(stmt)
    register_vector(conn)
```

But there are errors happening like:

```
Exception ignored in: <function ConnectionPool.__del__ at 0xffff68550d60>
Traceback (most recent call last):
  File "/app/__pypackages__/3.11/lib/psycopg_pool/pool.py", line 109, in __del__
    self._stop_workers()
  File "/app/__pypackages__/3.11/lib/psycopg_pool/pool.py", line 463, in _stop_workers
    gather(sched_runner, *workers, timeout=timeout)
  File "/app/__pypackages__/3.11/lib/psycopg_pool/_acompat.py", line 163, in gather
    t.join(timeout)
  File "/usr/local/lib/python3.11/threading.py", line 1116, in join
    raise RuntimeError("cannot join current thread")
RuntimeError: cannot join current thread
``` 

and in database:

```
2024-04-02 22:22:47.078 UTC [78] ERROR:  duplicate key value violates unique constraint "pg_extension_name_index"
```

The second one happens when there are more than one worker configured in the pool (default is 3), but the first one happens only when the configuration is inside a singleton class like this:

```
class PGVectorDocumentStore:

    _instance = None
    _lock = threading.Lock()

    def __init__(self):
        self._pool = ConnectionPool(
            kwargs=pgvectorstore_config(),
            max_size=20,
            check=ConnectionPool.check_connection,
            configure=self.register_pgvector,
            open=True
        )

   def __new__(cls):
        # Adding Singleton for only one connection and database configuration
        with cls._lock:
            if cls._instance is None:
                cls._instance = super().__new__(cls)
        return cls._instance
```

if I remove `__new__` function, than the error stops, but I need only one pool and not a new one every time

**Comment by dmvieira** [comment]
I did here a workaround that solved errors and keep a single pool. Start pool in `__new__` once for solving second one:

```python
   def __new__(cls):
        # Adding Singleton for only one connection and database configuration
        with cls._lock:
            if cls._instance is None:
                cls._pool = ConnectionPool(
                    kwargs=pgvectorstore_config(),
                    max_size=20,
                    check=ConnectionPool.check_connection,
                    configure=cls.register_pgvector,
                    open=True
                )
                cls._instance = super().__new__(cls)
        return cls._instance
```

Add lock inside `register_vector`, solving multi worker configuration (first error):

```python
def register_pgvector(cls, conn: Connection):
    with cls._lock():
        stmt = 'CREATE EXTENSION IF NOT EXISTS vector'
        with conn.cursor() as cur:
            cur.execute(stmt)
        register_vector(conn)
```

**Comment by ankane** [comment]
Hi @dmvieira, I'd recommend running `CREATE EXTENSION` with your schema / migration code rather than on every connection.

**Comment by dmvieira** [comment]
Hey @ankane , for some reason it requires every new connection too. It throws an exception:

`error connecting in 'pool-1': vector type not found in the database`

**Comment by ankane** [comment]
Make sure you're committing the transaction.

https://www.psycopg.org/psycopg3/docs/basic/transactions.html

**Comment by dmvieira** [comment]
It's already configured with autocommit 🤔 ... it's really necessary?

**Comment by ankane** [comment]
If it's not persisting, then yes. I'd recommend connecting to your database with `psql` to check:

```sql
SELECT extversion FROM pg_extension WHERE extname = 'vector';
```
